"""
Pydantic response models for the ICU Step-Down Readiness API.

All fields use explicit types and defaults — no implicit Optional via None.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel

from .. import __version__


# ---------------------------------------------------------------------------
# Shared
# ---------------------------------------------------------------------------


class VersionOut(BaseModel):
    version: str

    @classmethod
    def from_metadata(cls) -> "VersionOut":
        return cls(version=__version__)


class FactorOut(BaseModel):
    """A single SHAP-derived clinical factor, human-labelled and direction-corrected."""

    name: str
    """Human-readable label (e.g. 'on vasopressors', 'GCS (last)')."""

    direction: str
    """'supports' (positive readiness signal) or 'risk' (negative signal)."""

    magnitude: float
    """Absolute SHAP value — higher = more influential."""


# ---------------------------------------------------------------------------
# GET /api/census
# ---------------------------------------------------------------------------


class CensusPatient(BaseModel):
    """Summary row for one ICU patient in the census ranked list."""

    icustay_id: str
    subject_id: str
    age: float
    los: float
    """ICU length of stay in days (may be fractional)."""

    readiness_score: float
    """Raw model output — a ranking signal, NOT a probability (clusters ~0.44–0.53)."""

    readiness_index: int
    """Relative readiness index (0–100): percentile rank within today's census."""

    band: str
    """'Ready' (index >= 66), 'Borderline' (33–65), or 'Not ready' (< 33)."""

    on_vasopressors: bool
    on_ventilator: bool

    top_factors: list[FactorOut]
    """Top 3 factors (by magnitude) driving this patient's score."""


class CensusResponse(BaseModel):
    """Response for GET /api/census."""

    patients: list[CensusPatient]
    """Patients ranked by readiness_index descending."""

    total: int
    generated_at: str
    """ISO-8601 UTC timestamp when this response was generated."""


# ---------------------------------------------------------------------------
# GET /api/patients/{icustay_id}
# ---------------------------------------------------------------------------


class VitalPoint(BaseModel):
    """Single time-stamped vital sign reading."""

    charttime: datetime
    vital_name: str
    """Short name: 'hr', 'sbp', 'dbp', 'spo2', 'temp', 'rr', 'gcs', etc."""

    value: float


class PatientFeatures(BaseModel):
    """Patient demographics and latest clinical features."""

    icustay_id: str
    subject_id: str
    age: float
    los: float
    on_vasopressors: bool
    on_ventilator: bool
    hr_mean: float | None
    sbp_mean: float | None
    dbp_mean: float | None
    spo2_mean: float | None
    spo2_min: float | None
    temp_c_mean: float | None
    rr_mean: float | None
    gcs_last: float | None
    lactate_last: float | None


class PatientDetail(BaseModel):
    """Response for GET /api/patients/{icustay_id}."""

    features: PatientFeatures
    vitals: list[VitalPoint]
    """Recent vital signs time series from census_vitals (up to 500 rows)."""

    readiness_score: float
    readiness_index: int
    band: str
    factors: list[FactorOut]
    """Full factor list from the model (top-5 by magnitude, direction-corrected)."""

    narrative: str
    """Gen AI clinical summary generated by LLaMA-3.3-70B."""

    lactate_note: str | None
    """Present when lactate_last is a top factor — explains the measured-vs-null signal."""


# ---------------------------------------------------------------------------
# GET /api/analytics
# ---------------------------------------------------------------------------


class BandCount(BaseModel):
    band: str
    count: int
    pct: float
    """Percentage of current census in this band (0–100)."""


class FeatureImportanceItem(BaseModel):
    feature: str
    """Human-readable label."""

    importance: float
    """Mean |SHAP| value from the global feature importance analysis."""


class AnalyticsResponse(BaseModel):
    """Response for GET /api/analytics."""

    total_census: int
    band_distribution: list[BandCount]
    """Counts and percentages for Ready / Borderline / Not ready."""

    feature_importance: list[FeatureImportanceItem]
    """Global feature importance (top-10) from the v2 model evaluation."""

    avg_los_by_band: dict[str, float]
    """Average ICU length of stay (days) per readiness band."""

    vent_rate: float
    """Fraction of current census on ventilator (0–1)."""

    vasopressor_rate: float
    """Fraction of current census on vasopressors (0–1)."""

    generated_at: str
